### ISSUE TITLE
Cleanup and PHP 7.2 Support

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/zf1-php-7.2-support#1]
To simplify current work and future maintenance of ZF1, investigate possibility of removal of ZF1 components that are not used in Magento 2 ([2.3-develop](https://github.com/magento/magento2/tree/2.3-develop)).
As a next possible step, investigate efforts necessary to update remaining components.
And for all components that can't be either removed or updated, investigate efforts necessary to support PHP 7.2.

AC:
- list of components that can be safely removed
- list of components that can be easily upgraded to ZF 2/3
   - include details of the necessary effort
- list of components that should be fixed to support PHP 7.2
   - include details of the necessary effort

**Comment by dmanners** [comment]
I know from experience that:

`Zend_Captcha` could be removed as it has already been updated to the ZF2 version. https://github.com/magento/magento2/pull/8356 I am not sure if that could also be updated to the latest version also.

`Zend_Json` cannot sadly be removed as yet though it is only used in https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Json/Decoder.php and https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Json/Encoder.php which are both deprecated. We would have to update the usage of these classes as well as https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Json/Helper/Data.php before we could remove `Zend_Json`

**Comment by buskamuza** [comment]
Thanks, @dmanners .

I think we should be able to remove all deprecated Json functionality in 2.3. This means we can remove Zend_Json.
