### ISSUE TITLE
Remove Zend_Service from Zend_Currency

### ISSUE THREAD

**Issue by bbatsche** [magento-engcom/zf1-php-7.2-support#12]
Magento has a hard dependency on `Zend_Currency` that cannot be removed at this time. However, `Zend_Currency` has a dependency on `Zend_Service` that may be removed. This feature allowed for automatic currency conversions between different types, a function that has not been used within Magento or the broader marketplace. Removing this dependency would allow for us to eliminate `Zend_Service` entirely, as well as several other Zend modules that depend on it exclusively.

1. Remove the `'service`' option from `Zend_Service`
1. Remove the `getService()` method from `Zend_Service`
1. Remove the `setService()` method from `Zend_Service`
1. Modify the `_exchangeCurrency()` method in `Zend_Service`
    1. The `$rate` should always be `1`.
    1. Remove checking for currency types.

**Comment by buskamuza** [comment]
`Zend_Service` usages is eliminated and the library is removed from zf1.
