### ISSUE TITLE
Not 7.2 compatible

### ISSUE THREAD

**Issue by sshilko** [magento-engcom/zf1-php-7.2-support#16]
https://github.com/magento-engcom/zf1-php-7.2-support/blob/master/library/Zend/Db/Table/Abstract.php#L1307

Throws warnings
`$keyValuesCount = count($keyValues);`

**Comment by buskamuza** [comment]
@sshilko, thanks for reporting.
Could you please provide a scenario you get warnings for?

**Comment by sshilko** [comment]
By performing search with any Zend_Db_Table using find() providing simple argument like:
I.e. i look for row numner 10
`find(10);`

this resolves in func_get_args() as

`[0 => 10]`

further trying to do 
`$keyValues = 10;`
`$keyValuesCount = count($keyValues);`

Throws error in 7.2. as 10 is integer and not Countable or Array

https://github.com/magento-engcom/zf1-php-7.2-support/pull/17
