### ISSUE TITLE
Remove unused libraries

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/zf1-php-7.2-support#2]
The following libraries are note used in Magento CE/EE/B2B and in Marketplace extensions:
- Zend_Cloud
- Zend_CodeGenerator
- Zend_EventManager
- Zend_Gdata
- Zend_Markup
- Zend_Mobile
- Zend_Queue
- Zend_Stdlib
- Zend_Tag
- Zend_Test
- Zend_Tool

Please verify that the listed dependencies are not used in other libs that are used in Magento.

Here is the full list of unused libs (including ones that are dependencies for other libs):
- Zend_Amf
- Zend_Auth
- Zend_Captcha
- Zend_Cloud
- Zend_CodeGenerator
- Zend_Dojo
- Zend_EventManager
- Zend_Form
- Zend_Gdata
- Zend_Layout
- Zend_Ldap
- Zend_Markup
- Zend_Memory
- Zend_Mobile
- Zend_Navigation
- Zend_Paginator
- Zend_ProgressBar
- Zend_Queue
- Zend_Session
- Zend_Stdlib
- Zend_Tag
- Zend_Test
- Zend_Text
- Zend_TimeSync
- Zend_Tool
- Zend_Wildfire
- Zend_Xml

**Comment by bbatsche** [comment]
What do you mean by "removing" these libraries? Like, should their code be removed from the Magento fork of ZF1?

**Comment by buskamuza** [comment]
The unused libs list is calculated by this script: https://gist.github.com/buskamuza/7eb14e126efd38f5f0ff58d4791db988
